# ============================================================
# Qubes OS 4.3 Inventory
# ============================================================
# - Use qube names exactly as shown in `qvm-ls`
# - Groups represent roles (vpn, gpu, secure), not distros
# - Put uncategorized qubes in [misc] until they get a real role
# ============================================================

[all:vars]
latest_debian=debian-13-xfce
latest_fedora=fedora-42-xfce
latest_whonix_gateway=whonix-gateway-18
latest_whonix_workstation=whonix-workstation-18

[appvms]
# parent group (membership via :children)

[appvms:children]
android_appvms
linux_appvms
servicevm_appvms
windows_appvms

[appvms:vars]
klass=AppVM
# Defaults, unless overridden in-line:
label=orange
netvm=sys-firewall-full-internet
#template_to_use=fedora-42-xfce
template_to_use=latest_fedora
# default did not work, see: https://github.com/QubesOS/qubes-issues/issues/10504
#netvm=default

# --------------------
# Android Qubes, such as Waydroid
# --------------------
[android]
# parent group (membership via :children)

[android:children]
android_appvms
android_templatevms

[android_appvms]
maple-idle-rpg template_to_use=d13-waydroid-arm

# --------------------
# Qubes with GPU Passthrough (boot one at a time)
# --------------------
[gpu_passthrough]
# parent group (membership via :children)

[gpu_passthrough:children]
gpu_linux
gpu_windows

[gpu_linux]
droid-vscode-gpu template_to_use=debian-13-droid-vscode-gpu
steam-debian template_to_use=debian-13-gaming

[gpu_windows]
romhacking-hma template_to_use=win10-pro-gpu-passthrough
win10-gaming template_to_use=win10-pro-gpu-passthrough
# The windows templates themselves also use GPU passthrough
win10-pro-gpu-passthrough

# --------------------
# Linux AppVMs without another category
# --------------------
[linux_appvms]
anon-whonix template_to_use=latest_whonix_workstation
banking template_to_use=latest_whonix_workstation
cursor-ide template_to_use=fedora-42-cursor
discord template_to_use=archlinux-closed-source
personal
signal template_to_use=archlinux-signal
spotify template_to_use=archlinux-closed-source
untrusted
vault
windows-mgmt
work

# --------------------
# StandaloneVMs
# --------------------
[standalonevms]
# parent group (membership via :children)

[standalonevms:vars]
klass=StandaloneVM
# Defaults, unless overridden in-line:
label=gray
netvm=sys-firewall-full-internet
# default did not work, see: https://github.com/QubesOS/qubes-issues/issues/10504
#netvm=default

[standalonevms:children]
windows_standalonevms

[windows_standalonevms]
WinXP-32bit
WinXP-64bit

# --------------------
# ServiceVMs
# --------------------
[servicevm_appvms]
# parent group (membership via :children)

[servicevm_appvms:children]
net_providers
usb_providers

[servicevm_appvms:vars]
# Defaults, unless overridden in-line:
label=green
netvm=""

# --------------------
# TemplateVMs
# --------------------
[templatevms]
# parent group (membership via :children)

[templatevms:vars]
klass=TemplateVM
netvm=""
# Defaults, unless overridden in-line:
label=black

[templatevms:children]
android_templatevms
community_templatevms
custom_templatevms
default_templatevms
derivative_templatevms
windows_templatevms

# Android Templates
[android_templatevms]
d13-waydroid-arm
d13-waydroid-x86

# Default Templates on install
[community_templatevms]
archlinux template_to_use=""

# Custom Templates per forum guides
[custom_templatevms]
# currently a parent group (membership via :children), but not necessarily by design
#openbsd
#ubuntu, etc

[custom_templatevms:children]
android_templatevms

# Default Templates on install
[default_templatevms]
debian-13-xfce
fedora-42-xfce
whonix-gateway-18
whonix-workstation-18

# Templates forked from other Templates
[derivative_templatevms]
archlinux-closed-source
archlinux-signal
debian-13-droid-vscode-gpu
debian-13-gaming
debian-13-openvpn
fedora-42-adb-and-codecs
fedora-42-ansible
fedora-42-cursor
fedora-42-vpn
fedora-42-tailscale

# Windows Templates
[windows_templatevms]
win10-pro-x64
win10-pro-gpu-passthrough
win7-ult-x64

# --------------------
# NetVM qubes (sometimes useful for passthrough)
# --------------------
[net_providers]
sys-firewall
sys-firewall-localnet
sys-net

[net_providers:children]
vpn_net_providers

[vpn_net_providers]
sys-vpn template_to_use=debian-13-openvpn
sys-tailnet template_to_use=fedora-42-tailscale
sys-whonix template_to_use=latest_whonix_gateway

# --------------------
# Qubes with a passed through USB controller or device (watch for conflicts when booting)
# --------------------
[usb_passthrough]
android-adb template_to_use=fedora-42-adb-and-codecs

# --------------------
# USB controller qubes (sometimes useful for passthrough)
# --------------------
[usb_providers]
sys-usb
sys-usb-2
sys-usb-3

# --------------------
# Windows Qubes
# --------------------
[windows]
# parent group (membership via :children)

[windows:children]
windows_appvms
windows_standalonevms
windows_templatevms

[windows:vars]
# Defaults, unless overridden in-line:
label=blue

# Is any of this useful for [windows:vars]?:
#ansible_connection=winrm
#ansible_user=Administrator
#ansible_password=CHANGE_ME
#ansible_winrm_transport=ntlm
#ansible_winrm_server_cert_validation=ignore

[windows_appvms]
win10-romhacking-hma template_to_use=win10-pro-x64
win10-gaming template_to_use=win10-pro-gpu-passthrough
win7-ult-x64-appvm template_to_use=win7-ult-x64
